type TimeOfDay = "morning" | "afternoon" | "evening";

const GREETINGS: Record<string, Record<TimeOfDay, string[]>> = {
  en: {
    morning: [
      "Good morning",
      "Rise and shine",
      "Morning, sunshine",
      "Top of the morning",
      "Wakey wakey",
      "Hello, early bird",
      "Fresh start today",
      "Up and at it",
      "A brand new day",
      "Look who's up",
    ],
    afternoon: [
      "Good afternoon",
      "Hey there",
      "How's your day going?",
      "Afternoon vibes",
      "Still going strong",
      "Halfway through the day",
      "Hello again",
      "Back for more?",
      "Let's keep going",
      "Nice to see you",
    ],
    evening: [
      "Good evening",
      "Evening, friend",
      "Winding down?",
      "Hello, night owl",
      "One more round?",
      "Burning the midnight oil",
      "Back at it tonight",
      "Evening session",
      "Still at it?",
      "Late night learner",
    ],
  },
  cs: {
    morning: [
      "Dobré ráno",
      "Ranní ptáče",
      "Vstávej, slunce svítí",
      "Krásné ráno",
      "Nový den, nová šance",
      "Vzhůru do toho",
      "Čerstvé ráno",
      "Hezké ránko",
      "Ráno dělá den",
      "Vítej, ranní ptáče",
    ],
    afternoon: [
      "Dobré odpoledne",
      "Ahoj zase",
      "Jak jde den?",
      "Odpolední porce",
      "Ještě nekonči",
      "Půlka dne za námi",
      "Tak co, jedeme?",
      "Zpátky v akci",
      "Pokračujem dál",
      "Hezké odpoledne",
    ],
    evening: [
      "Dobrý večer",
      "Večerní sova",
      "Ještě jedna lekce?",
      "Noční směna",
      "Klidný večer",
      "Večer jako stvořený k učení",
      "Pozdní trénink",
      "Hezký večer",
      "Ještě to dáme",
      "Večerní pohoda",
    ],
  },
  de: {
    morning: [
      "Guten Morgen",
      "Frühaufsteher!",
      "Morgenstund hat Gold im Mund",
      "Schönen Morgen",
      "Auf geht's",
      "Guten Start",
      "Frisch und munter",
      "Raus aus den Federn",
      "Ein neuer Tag",
      "Wach auf, Sonnenschein",
    ],
    afternoon: [
      "Guten Tag",
      "Schönen Nachmittag",
      "Na, wie läuft's?",
      "Weiter geht's",
      "Hallo nochmal",
      "Zurück am Start",
      "Nachmittagsrunde",
      "Mach weiter so",
      "Schön, dich zu sehen",
      "Auf ein Neues",
    ],
    evening: [
      "Guten Abend",
      "Nachteule",
      "Noch eine Runde?",
      "Feierabend-Lernen",
      "Schönen Abend",
      "Abendprogramm",
      "Spätschicht",
      "Noch fleißig?",
      "Abendsession",
      "Gemütlicher Abend",
    ],
  },
  es: {
    morning: [
      "Buenos días",
      "Arriba el ánimo",
      "Buen despertar",
      "Mañana brillante",
      "A empezar el día",
      "Nuevo día, nueva oportunidad",
      "Madrugador",
      "Qué bonita mañana",
      "Despierta, campeón",
      "Vamos allá",
    ],
    afternoon: [
      "Buenas tardes",
      "Hola de nuevo",
      "¿Qué tal el día?",
      "Seguimos adelante",
      "Tarde productiva",
      "De vuelta a ello",
      "¿Una más?",
      "Buena tarde para aprender",
      "Aquí seguimos",
      "¡Vamos!",
    ],
    evening: [
      "Buenas noches",
      "Noctámbulo",
      "¿Una ronda más?",
      "Sesión nocturna",
      "Tranquila noche",
      "Aprendiendo de noche",
      "Aún despierto",
      "Noche de estudio",
      "Última sesión",
      "Buena noche para aprender",
    ],
  },
  fr: {
    morning: [
      "Bonjour",
      "Bien le bonjour",
      "Salut, lève-tôt",
      "Belle matinée",
      "Debout là-dedans",
      "Nouveau jour, nouvelle chance",
      "Frais et dispo",
      "Quelle belle matinée",
      "C'est parti",
      "Réveil en douceur",
    ],
    afternoon: [
      "Bon après-midi",
      "Re-bonjour",
      "On continue ?",
      "Bel après-midi",
      "De retour",
      "Encore un peu ?",
      "L'après-midi est à nous",
      "Toujours motivé ?",
      "Allez, on y va",
      "Pas mal comme journée",
    ],
    evening: [
      "Bonsoir",
      "Chouette de nuit",
      "Encore une leçon ?",
      "Session du soir",
      "Belle soirée",
      "Couche-tard",
      "Un dernier tour ?",
      "Soirée studieuse",
      "Pas encore au lit ?",
      "Bonne soirée",
    ],
  },
  it: {
    morning: [
      "Buongiorno",
      "Sveglia, campione",
      "Bella mattinata",
      "Si parte",
      "Nuovo giorno, nuova energia",
      "Mattiniero",
      "Che bella mattina",
      "Buon risveglio",
      "Pronto per iniziare",
      "Forza e coraggio",
    ],
    afternoon: [
      "Buon pomeriggio",
      "Ciao di nuovo",
      "Si continua",
      "Come va la giornata?",
      "Di nuovo qui",
      "Andiamo avanti",
      "Pomeriggio produttivo",
      "Ancora una volta",
      "Bentornato",
      "Non mollare",
    ],
    evening: [
      "Buonasera",
      "Nottambulo",
      "Un altro giro?",
      "Sessione serale",
      "Bella serata",
      "Ancora sveglio?",
      "Studio notturno",
      "Ultima lezione?",
      "Serata tranquilla",
      "Buona serata",
    ],
  },
  pt: {
    morning: [
      "Bom dia",
      "Acorda, campeão",
      "Bela manhã",
      "Vamos lá",
      "Novo dia, nova chance",
      "Madrugador",
      "Que manhã bonita",
      "Hora de começar",
      "Bora?",
      "Mais um dia",
    ],
    afternoon: [
      "Boa tarde",
      "De volta",
      "Vamos continuar?",
      "Tarde produtiva",
      "Ainda firme",
      "Mais uma rodada",
      "Como vai o dia?",
      "Seguimos",
      "Boa tarde pra aprender",
      "Voltou!",
    ],
    evening: [
      "Boa noite",
      "Coruja noturna",
      "Mais uma lição?",
      "Sessão noturna",
      "Boa noite pra estudar",
      "Ainda acordado?",
      "Noite de estudo",
      "Última sessão?",
      "Noite tranquila",
      "Bora fechar o dia",
    ],
  },
  nl: {
    morning: [
      "Goedemorgen",
      "Vroege vogel",
      "Fijne ochtend",
      "Opstaan en gaan",
      "Nieuwe dag, nieuwe kans",
      "Wakker worden",
      "Lekker fris",
      "Aan de slag",
      "Mooie morgen",
      "Klaar voor vandaag?",
    ],
    afternoon: [
      "Goedemiddag",
      "Hallo weer",
      "Hoe gaat het?",
      "We gaan door",
      "Nog een rondje?",
      "Terug van weggeweest",
      "Fijne middag",
      "Productieve middag",
      "Lekker bezig",
      "Doorgaan!",
    ],
    evening: [
      "Goedenavond",
      "Nachtuil",
      "Nog eentje?",
      "Avondsessie",
      "Fijne avond",
      "Nog even doorgaan",
      "Laatavond-leren",
      "Nog wakker?",
      "Rustige avond",
      "Laatste ronde?",
    ],
  },
  pl: {
    morning: [
      "Dzień dobry",
      "Ranny ptaszek",
      "Piękny poranek",
      "Wstawaj, słoneczko",
      "Nowy dzień, nowa szansa",
      "Pora wstawać",
      "Świeży start",
      "Czas na naukę",
      "Miłego poranka",
      "Do dzieła",
    ],
    afternoon: [
      "Dzień dobry",
      "Hej, znowu tu",
      "Jak leci dzień?",
      "Jedziemy dalej",
      "Popołudniowa runda",
      "Wracamy do nauki",
      "Jeszcze trochę?",
      "Nie zwalniaj tempa",
      "Dobra robota",
      "Dalej naprzód",
    ],
    evening: [
      "Dobry wieczór",
      "Nocna sowa",
      "Jeszcze jedna lekcja?",
      "Wieczorna sesja",
      "Miłego wieczoru",
      "Wieczorne powtórki",
      "Jeszcze nie śpisz?",
      "Nocna nauka",
      "Ostatnia runda?",
      "Spokojny wieczór",
    ],
  },
  sk: {
    morning: [
      "Dobré ráno",
      "Ranné vtáča",
      "Krásne ráno",
      "Vstávaj, svieti slnko",
      "Nový deň, nová šanca",
      "Čerstvé ráno",
      "Poďme na to",
      "Hore sa",
      "Pekné ránko",
      "Ráno robí deň",
    ],
    afternoon: [
      "Dobré popoludnie",
      "Ahoj znova",
      "Ako ide deň?",
      "Poobedná porcia",
      "Pokračujeme ďalej",
      "Ešte nekončíme",
      "Tak čo, ideme?",
      "Späť v akcii",
      "Pekné popoludnie",
      "Ďalšia runda",
    ],
    evening: [
      "Dobrý večer",
      "Večerná sova",
      "Ešte jedna lekcia?",
      "Nočná smena",
      "Pokojný večer",
      "Večer ako stvorený na učenie",
      "Neskoro, ale nevadí",
      "Pekný večer",
      "Ešte to dáme",
      "Večerná pohoda",
    ],
  },
  uk: {
    morning: [
      "Доброго ранку",
      "Ранній птах",
      "Гарного ранку",
      "Вставай, сонечко",
      "Новий день",
      "Свіжий ранок",
      "Час починати",
      "Прекрасний ранок",
      "Уперед",
      "Доброго дня",
    ],
    afternoon: [
      "Добрий день",
      "Привіт знову",
      "Як минає день?",
      "Продовжуємо",
      "Ще трохи?",
      "Повернулись",
      "Гарний день",
      "Не зупиняйся",
      "Далі більше",
      "Продуктивний день",
    ],
    evening: [
      "Добрий вечір",
      "Нічна сова",
      "Ще один урок?",
      "Вечірня сесія",
      "Гарного вечора",
      "Ще не спиш?",
      "Пізня зміна",
      "Вечірнє навчання",
      "Останній раунд?",
      "Спокійного вечора",
    ],
  },
  ru: {
    morning: [
      "Доброе утро",
      "Ранняя пташка",
      "Прекрасное утро",
      "Вставай, солнышко",
      "Новый день",
      "Свежее утро",
      "Пора начинать",
      "Поехали",
      "Утро доброе",
      "За дело",
    ],
    afternoon: [
      "Добрый день",
      "Привет снова",
      "Как проходит день?",
      "Продолжаем",
      "Ещё немного?",
      "Вернулись",
      "Хороший день",
      "Не останавливайся",
      "Дальше больше",
      "Продуктивный день",
    ],
    evening: [
      "Добрый вечер",
      "Ночная сова",
      "Ещё один урок?",
      "Вечерняя сессия",
      "Хорошего вечера",
      "Ещё не спишь?",
      "Поздняя смена",
      "Вечернее занятие",
      "Последний раунд?",
      "Спокойного вечера",
    ],
  },
  ja: {
    morning: [
      "おはようございます",
      "おはよう",
      "いい朝ですね",
      "今日も頑張ろう",
      "新しい一日",
      "朝の勉強",
      "早起きは三文の徳",
      "さあ始めよう",
      "いい天気ですね",
      "元気な朝",
    ],
    afternoon: [
      "こんにちは",
      "お疲れ様",
      "午後も頑張ろう",
      "調子はどう？",
      "また来たね",
      "続けよう",
      "いい午後",
      "もう少し？",
      "頑張ってるね",
      "午後の部",
    ],
    evening: [
      "こんばんは",
      "夜型ですね",
      "もう一回？",
      "夜の勉強",
      "お疲れ様でした",
      "まだ起きてる？",
      "夜更かし",
      "最後の一回",
      "静かな夜",
      "いい夜ですね",
    ],
  },
  ko: {
    morning: [
      "좋은 아침이에요",
      "일찍 일어났네요",
      "상쾌한 아침",
      "오늘도 파이팅",
      "새로운 하루",
      "아침 공부",
      "좋은 하루 시작",
      "시작해 볼까요?",
      "힘찬 아침",
      "잘 잤어요?",
    ],
    afternoon: [
      "안녕하세요",
      "오후도 화이팅",
      "다시 왔네요",
      "계속해 볼까요?",
      "좋은 오후",
      "조금 더?",
      "잘하고 있어요",
      "오후 시간",
      "돌아왔군요",
      "열심히 하네요",
    ],
    evening: [
      "좋은 저녁이에요",
      "야행성이군요",
      "한 번 더?",
      "저녁 공부",
      "아직 안 잤어요?",
      "밤 공부",
      "마지막 라운드?",
      "조용한 밤",
      "좋은 밤이에요",
      "수고했어요",
    ],
  },
  zh: {
    morning: [
      "早上好",
      "早安",
      "起得真早",
      "新的一天",
      "早起的鸟儿",
      "今天也加油",
      "美好的早晨",
      "开始学习吧",
      "精神满满",
      "早起真棒",
    ],
    afternoon: [
      "下午好",
      "又来了",
      "继续加油",
      "下午时光",
      "再来一轮？",
      "不错哦",
      "今天过得怎样？",
      "回来了",
      "下午的学习",
      "坚持就是胜利",
    ],
    evening: [
      "晚上好",
      "夜猫子",
      "再来一课？",
      "晚间学习",
      "还没睡？",
      "夜深了",
      "最后一轮？",
      "安静的夜晚",
      "晚安学习",
      "辛苦了",
    ],
  },
  sv: {
    morning: [
      "God morgon",
      "Morgonpigg?",
      "Fin morgon",
      "Ny dag, ny chans",
      "Dags att börja",
      "Uppe redan?",
      "Fräsch morgon",
      "Morgonstund har guld i mund",
      "Vaken och pigg",
      "Kör igång",
    ],
    afternoon: [
      "God eftermiddag",
      "Hej igen",
      "Hur mår du?",
      "Vi kör vidare",
      "En runda till?",
      "Tillbaka igen",
      "Fin eftermiddag",
      "Produktiv dag",
      "Fortsätt så",
      "Bra jobbat",
    ],
    evening: [
      "God kväll",
      "Nattugla",
      "En till?",
      "Kvällssession",
      "Fin kväll",
      "Fortfarande vaken?",
      "Sena kvällen",
      "Sista rundan?",
      "Lugn kväll",
      "Bra kämpat",
    ],
  },
  no: {
    morning: [
      "God morgen",
      "Tidlig oppe?",
      "Fin morgen",
      "Ny dag, ny sjanse",
      "Klar for dagen?",
      "Morgenfrisk",
      "Opp og stå",
      "La oss begynne",
      "Strålende morgen",
      "I gang igjen",
    ],
    afternoon: [
      "God ettermiddag",
      "Hei igjen",
      "Hvordan går det?",
      "Vi fortsetter",
      "En runde til?",
      "Tilbake igjen",
      "Fin ettermiddag",
      "Produktiv dag",
      "Fortsett sånn",
      "Bra jobba",
    ],
    evening: [
      "God kveld",
      "Nattugle",
      "En til?",
      "Kveldsøkt",
      "Fin kveld",
      "Fortsatt våken?",
      "Sen kveld",
      "Siste runde?",
      "Rolig kveld",
      "Godt jobba",
    ],
  },
  da: {
    morning: [
      "Godmorgen",
      "Tidlig oppe?",
      "Dejlig morgen",
      "Ny dag, ny chance",
      "Klar til dagen?",
      "Morgenfrisk",
      "Op og stå",
      "Lad os begynde",
      "Strålende morgen",
      "I gang igen",
    ],
    afternoon: [
      "God eftermiddag",
      "Hej igen",
      "Hvordan går det?",
      "Vi fortsætter",
      "En runde mere?",
      "Tilbage igen",
      "Fin eftermiddag",
      "Produktiv dag",
      "Fortsæt sådan",
      "Godt gået",
    ],
    evening: [
      "Godaften",
      "Natuglen",
      "En mere?",
      "Aftensession",
      "Dejlig aften",
      "Stadig vågen?",
      "Sen aften",
      "Sidste runde?",
      "Rolig aften",
      "Godt klaret",
    ],
  },
  fi: {
    morning: [
      "Hyvää huomenta",
      "Aamuvirkku",
      "Kaunis aamu",
      "Uusi päivä",
      "Aamu-uninen?",
      "Herätys",
      "Aloitetaan",
      "Raikas aamu",
      "Hyvä aamu",
      "Mennään",
    ],
    afternoon: [
      "Hyvää iltapäivää",
      "Hei taas",
      "Miten menee?",
      "Jatketaan",
      "Vielä yksi?",
      "Takaisin taas",
      "Hyvä iltapäivä",
      "Tuottava päivä",
      "Hienosti menee",
      "Jatka samaan malliin",
    ],
    evening: [
      "Hyvää iltaa",
      "Yökyöpeli",
      "Vielä yksi?",
      "Iltasessio",
      "Mukava ilta",
      "Vielä hereillä?",
      "Myöhäinen ilta",
      "Viimeinen kierros?",
      "Rauhallinen ilta",
      "Hyvin tehty",
    ],
  },
  tr: {
    morning: [
      "Günaydın",
      "Erken kalktın",
      "Güzel bir sabah",
      "Yeni gün, yeni fırsat",
      "Hazır mısın?",
      "Taze bir başlangıç",
      "Haydi başlayalım",
      "Sabah enerjisi",
      "Güne merhaba",
      "Uyanık mısın?",
    ],
    afternoon: [
      "İyi günler",
      "Tekrar merhaba",
      "Nasıl gidiyor?",
      "Devam edelim",
      "Bir tur daha?",
      "Geri döndün",
      "Güzel öğleden sonra",
      "Verimli bir gün",
      "Böyle devam",
      "Aferin",
    ],
    evening: [
      "İyi akşamlar",
      "Gece kuşu",
      "Bir tane daha?",
      "Akşam dersi",
      "Güzel akşam",
      "Hâlâ uyanık mısın?",
      "Geç saatler",
      "Son tur?",
      "Sakin bir akşam",
      "İyi çalıştın",
    ],
  },
  ar: {
    morning: [
      "صباح الخير",
      "صباح النور",
      "صباح الورد",
      "يوم جديد",
      "صباح مشرق",
      "هيا نبدأ",
      "صباح الهمة",
      "صباح جميل",
      "بداية جديدة",
      "نشيط اليوم",
    ],
    afternoon: [
      "مساء الخير",
      "أهلاً من جديد",
      "كيف يومك؟",
      "نكمل",
      "جولة أخرى؟",
      "عدت مجدداً",
      "مساء جميل",
      "يوم مثمر",
      "استمر",
      "أحسنت",
    ],
    evening: [
      "مساء الخير",
      "بومة الليل",
      "واحدة كمان؟",
      "درس مسائي",
      "مساء هادئ",
      "لسه صاحي؟",
      "وقت متأخر",
      "الجولة الأخيرة؟",
      "ليلة هادئة",
      "أحسنت اليوم",
    ],
  },
  hi: {
    morning: [
      "सुप्रभात",
      "शुभ प्रभात",
      "नया दिन, नई शुरुआत",
      "सुबह हो गई",
      "जल्दी उठे?",
      "ताज़ा सुबह",
      "चलो शुरू करें",
      "अच्छी सुबह",
      "तैयार हो?",
      "आज का दिन अच्छा होगा",
    ],
    afternoon: [
      "नमस्ते",
      "फिर से आए",
      "दिन कैसा जा रहा है?",
      "आगे बढ़ते हैं",
      "एक और राउंड?",
      "वापस आ गए",
      "अच्छी दोपहर",
      "बहुत अच्छे",
      "ऐसे ही चलते रहो",
      "शाबाश",
    ],
    evening: [
      "शुभ संध्या",
      "रात का उल्लू",
      "एक और?",
      "शाम की पढ़ाई",
      "अच्छी शाम",
      "अभी तक जागे हो?",
      "देर रात",
      "आखिरी राउंड?",
      "शांत शाम",
      "आज बहुत मेहनत की",
    ],
  },
};

function getTimeOfDay(): TimeOfDay {
  const hour = new Date().getHours();
  if (hour < 12) return "morning";
  if (hour < 18) return "afternoon";
  return "evening";
}

function dayHash(): number {
  const epoch = new Date(2024, 0, 1).getTime();
  const day = Math.floor((Date.now() - epoch) / 86_400_000);
  // simple hash so the sequence isn't just 0,1,2,3...
  let h = day * 2654435761;
  h = ((h >>> 16) ^ h) * 0x45d9f3b;
  h = (h >>> 16) ^ h;
  return Math.abs(h);
}

export function getGreeting(langCode: string): string {
  const time = getTimeOfDay();
  const pool = GREETINGS[langCode]?.[time] ?? GREETINGS.en[time];
  return pool[dayHash() % pool.length];
}
